### ISSUE TITLE
One Liner Adjustment

### ISSUE THREAD

**Issue by codybrouwers** [simon-engledew/gocmdpev#5]
The one liner you have in the README is appending EXPLAIN and it's arguments to every line of my query, adding a 1 to the sed command seems to fix it?

So from this ->
`pbpaste | sed 's/^/EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) /' | psql -qAt <DATABASE> | gocmdpev`

to ->
`pbpaste | sed '1s/^/EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) /' | psql -qAt <DATABASE> | gocmdpev`

**Comment by codybrouwers** [comment]
Also forgot to mention, I love this and am definitely going to be using it a lot, so thanks for all your work!

**Comment by rjschwartz** [comment]
In addition to enforcing only the first line,
I also had to add the `X` flag to psql to avoid `\timing` in my `.psqlrc`.

**Comment by simon-engledew** [comment]
Thanks guys, nice catches!
