### ISSUE TITLE
without ANALYZE?

### ISSUE THREAD

**Issue by rotten** [simon-engledew/gocmdpev#6]
I'm studying a query that takes about 12 hours to run.  I'm experimenting with different query planning constants and indexes to try to improve the query plan.  It isn't practical to do these experiments using ANALYZE in the EXPLAIN.

Would it be a hard hack to tweak gocmdpev to not require the query to actually run (just highlight the good and bad parts of the plan)... perhaps with a command line flag?

**Comment by rotten** [comment]
Actually that might work, even when I use this with ANALYZE (for shorter running queries), it seems the problem may be mostly that it doesn't work any more with PostgreSQL 10.

I don't have an older database to go back and try it against.

**Comment by simon-engledew** [comment]
Hey, I just tested it against Postgres 10.1 and it seems to work for me.

I think you can omit the `ANALYSE` and `BUFFERS` options and skip running the query? I tried it with a basic table and it seemed to work:

<img width="1235" alt="screen shot 2018-02-06 at 13 08 55" src="https://user-images.githubusercontent.com/14410/35861253-e9a48694-0b3e-11e8-932a-3e041b1618bf.png">

**Comment by rotten** [comment]
I always get this:

```
$  psql -f rsquery.sql | gocmdpev
2018/02/06 09:43:28 invalid character 'Q' looking for beginning of value

```
I noticed I had BUFFERS set in my explain statement, so I disabled that.
Same thing.

Now that I look more closely.
doh.
I wasn't using `-qXAt` 

Sorry about that.  I assumed it was just a migration to PostgreSQL 10 thing, which broke a few other tools without upgrading them.  It was just operator error.

**Comment by simon-engledew** [comment]
Glad it's working for you now ^_^
