### ISSUE TITLE
HTML output. Or AHA-compatibility

### ISSUE THREAD

**Issue by belonesox** [simon-engledew/gocmdpev#7]
I wish to output in colored HTML (for discussing/collaboration/etc).

Actually preformatted HTML block with inline coloring tags by «span» will be OK.

I tried to use https://github.com/theZiz/aha for this, but failed (no coloring detected by AHA…).

So please, make either
* HTML output
* Or color codes compatible with some software, that can convert output to HTML.

**Comment by simon-engledew** [comment]
Hi! Could you use the web-based tool this project is based on?

http://tatiyants.com/pev/

Or do you specifically need the command-line style output?

**Comment by belonesox** [comment]
OK, thank you.
