### ISSUE TITLE
Lack of python-binding documentation

### ISSUE THREAD

**Issue by eyaltrabelsi** [simon-engledew/gocmdpev#8]
Hi I am trying to use this amazing library via python and I am having troubles installing it.
Do I first need to clone this repo before running this 
"go build -buildmode=c-shared -o pycmdpev.so pybindings/*"

**Comment by eyaltrabelsi** [comment]
any update on this ?

**Comment by simon-engledew** [comment]
Check out the repository and try running `make python3`. If you have the python3 header files and a new enough version of Golang it should build the module and then test it in your Python interpreter.
